#!/bin/bash

revert() {
    xset dpms 0 0 0
}

trap revert HUP INT TERM
xset +dpms dpms 3 3 3

if [ ${1: -4} != ".png" ]; then
    magick convert $1 /tmp/bgg.png
    IMG=/tmp/bgg/png
else
    IMG=$1
fi

i3lock -b -n -u -i $IMG

revert

